name: Build and Test

on:
  pull_request:
  push:
    branches:
      - '*'
    tags:
      - 'v*'      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/checkout@v3
      - run: npm install --package-lock-only
      - run: npm ci
      - run: npm run build
      - run: npm run format-check
      - run: npm run lint
      - run: npm test
      - name: Create release
        uses: josephrodriguez/swift-release@v1-beta2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
